language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'iojs'
install:
  - npm install
  # node 0.10 doesn't automatically install peer dependencies.
  - npm install bunyan
after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'